/* make an array of projects title, description and 5 technologies */
const projects = [
  {
    title: 'land rover e-commerce',
    description: 'Full stack web application that allows the user to get information and appointments for their selected product with a solid database.',
    technologies: ['React & Redux', 'Ruby on Rails', 'API Endpoint', 'PostgreSQL'],
    repo: 'https://github.com/VelzckC0D3/Land-Rover-E-Commerce',
    demo: 'https://land-rover-e.netlify.app/',
    thumbnail: 'https://i.imgur.com/t3GYAkU.png',
    gallery: ['https://i.postimg.cc/9XB01rdR/land1.webp', 'https://i.postimg.cc/fy5bbrzj/land2.webp', 'https://i.postimg.cc/MHzTqSSp/land3.webp', 'https://i.postimg.cc/fRVkDdy3/land5.webp', 'https://i.postimg.cc/3rj8TBZf/land4.webp'],
    id: '1',
  },
  {
    title: 'WiseWallet',
    description: 'Full stack web application that allows the users to manage their finances through a well designed UI/UX Interface with a solid database.',
    technologies: ['React & Redux', 'Ruby on Rails', 'API Endpoint', 'PostgreSQL'],
    repo: 'https://github.com/VelzckC0D3/Budget_App',
    demo: 'https://rails-eb2s.onrender.com/',
    thumbnail: 'https://i.imgur.com/TTskEqc.png',
    gallery: ['https://i.postimg.cc/B6r8tcY7/wise1.webp', 'https://i.postimg.cc/NFRKX9Zs/wise2.webp', 'https://i.postimg.cc/zX1br7RV/wise3.webp', 'https://i.postimg.cc/MZBMNNHC/wise4.webp', 'https://i.postimg.cc/J4cy4XbK/wise5.webp'],
    id: '2',
  },
  {
    title: 'Velzck Shop',
    description: 'UI / UX design for a sneakers e-commerce, showcasing a responsive & addaptative design.',
    technologies: ['CSS', 'HTML', 'JavaScript', 'DOM'],
    repo: 'https://github.com/VelzckC0D3/Velzck_Shop',
    demo: 'https://velzckshop.netlify.app/',
    thumbnail: 'https://i.imgur.com/JPrPqMF.png',
    gallery: ['https://i.postimg.cc/NjR77Lqz/sneaker1.webp', 'https://i.postimg.cc/nLZKdZnc/sneaker2.webp', 'https://i.postimg.cc/tg53wfgd/sneaker3.webp'],
    id: '3',
  },
  {
    title: 'Game Collection',
    description: 'Mobile web application that ensures efficient global state management, modular components, and advanced JavaScript capabilities.',
    technologies: ['React & Redux', 'API Rest', 'DOM', 'ES6', 'Mobile First'],
    repo: 'https://github.com/VelzckC0D3/game_collection',
    demo: 'https://velzck-collection.netlify.app',
    thumbnail: 'https://i.imgur.com/1L6abUO.png',
    gallery: ['https://i.postimg.cc/C57D6rsB/game1.webp', 'https://i.postimg.cc/CMsj1dph/game2.webp'],
    id: '4',
  },
  {
    title: 'Conference Landing Page',
    description: 'Simple yet solid landing page for a conference, showcasing a responsive & addaptative design.',
    technologies: ['HTML', 'CSS', 'JavaScript', 'DOM'],
    repo: 'https://github.com/VelzckC0D3/Velzck_Festival',
    demo: 'https://velzck-festival.netlify.app/index.html',
    thumbnail: 'https://i.imgur.com/ojSG9I6.png',
    gallery: ['https://i.postimg.cc/bvjysxnd/festival1.webp', 'https://i.postimg.cc/25Fzv1dG/festival2.webp', 'https://i.postimg.cc/Qt8jqj03/festival3.webp', 'https://i.postimg.cc/j2CKGvp3/festival4.webp', 'https://i.postimg.cc/d3Xvvrvs/festival5.webp'],
    id: '5',
  },
  {
    title: 'Math Magicians',
    description: 'Mathematics web application that allows the user to make simple calculations, showcasing a responsive & addaptative design.',
    technologies: ['React', 'CSS', 'ES6', 'API'],
    repo: 'https://github.com/VelzckC0D3/math_magicians_react',
    demo: 'https://velzck-magician.netlify.app/',
    thumbnail: 'https://i.imgur.com/LSOLxy8.png',
    gallery: ['https://i.postimg.cc/FHK24Tnv/magician1.webp', 'https://i.postimg.cc/SxtHNcwM/magician2.webp', 'https://i.postimg.cc/QM9wBH3n/magician3.webp'],
    id: '6',
  },
];

export default projects;
