/* make an array of projects title, description and 5 technologies */
const projects = [
  {
    title: 'Project 1',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae aliquam ultricies, nunc nisl ultricies nunc, vitae aliquam nisl nisl vitae aliquam nisl.',
    technologies: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
    repo: 'http://www.repo.com/',
    demo: 'http://www.demo.com/',
    thumbnail: '../assets/project_img/project.webp',
    id: '1',
  },
  {
    title: 'Project 2',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae aliquam ultricies, nunc nisl ultricies nunc, vitae aliquam nisl nisl vitae aliquam nisl.',
    technologies: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
    repo: 'http://www.repo.com/',
    demo: 'http://www.demo.com/',
    thumbnail: '../assets/project_img/project.webp',
    id: '2',
  },
  {
    title: 'Project 3',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae aliquam ultricies, nunc nisl ultricies nunc, vitae aliquam nisl nisl vitae aliquam nisl.',
    technologies: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
    repo: 'http://www.repo.com/',
    demo: 'http://www.demo.com/',
    thumbnail: '../assets/project_img/project.webp',
    id: '3',
  },
  {
    title: 'Project 4',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae aliquam ultricies, nunc nisl ultricies nunc, vitae aliquam nisl nisl vitae aliquam nisl.',
    technologies: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
    repo: 'http://www.repo.com/',
    demo: 'http://www.demo.com/',
    thumbnail: '../assets/project_img/project.webp',
    id: '4',
  },
  {
    title: 'Project 5',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae aliquam ultricies, nunc nisl ultricies nunc, vitae aliquam nisl nisl vitae aliquam nisl.',
    technologies: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
    repo: 'http://www.repo.com/',
    demo: 'http://www.demo.com/',
    thumbnail: '../assets/project_img/project.webp',
    id: '5',
  },
  {
    title: 'Project 6',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae aliquam ultricies, nunc nisl ultricies nunc, vitae aliquam nisl nisl vitae aliquam nisl.',
    technologies: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
    repo: 'http://www.repo.com/',
    demo: 'http://www.demo.com/',
    thumbnail: '../assets/project_img/project.webp',
    id: '6',
  },

  {
    title: 'Project 7',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae aliquam ultricies, nunc nisl ultricies nunc, vitae aliquam nisl nisl vitae aliquam nisl.',
    technologies: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
    repo: 'http://www.repo.com/',
    demo: 'http://www.demo.com/',
    thumbnail: '../assets/project_img/project.webp',
    id: '7',
  },
  {
    title: 'Project 8',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae aliquam ultricies, nunc nisl ultricies nunc, vitae aliquam nisl nisl vitae aliquam nisl.',
    technologies: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
    repo: 'http://www.repo.com/',
    demo: 'http://www.demo.com/',
    thumbnail: '../assets/project_img/project.webp',
    id: '8',
  },
  {
    title: 'Project 9',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae aliquam ultricies, nunc nisl ultricies nunc, vitae aliquam nisl nisl vitae aliquam nisl.',
    technologies: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js', 'Express', 'MongoDB'],
    repo: 'http://www.repo.com/',
    demo: 'http://www.demo.com/',
    thumbnail: '../assets/project_img/project.webp',
    id: '9',
  },
];

export default projects;
